name: docker build

on:
  push:
    branches:
      - master

env:
  REPOSITORY: kumassy/foo-bar-images

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: cuda image
      run: |
        TAG=cuda10.0
        docker build -t ${REPOSITORY}:${TAG} --file cuda/Dockerfile .
        docker push ${REPOSITORY}:${TAG}

    - name: python image
      run: |
        TAG=python3.7
        docker build -t ${REPOSITORY}:${TAG} --file cuda/Dockerfile .
        docker push ${REPOSITORY}:${TAG}

    - name: cuda-python image
      run: |
        TAG=cuda10.0-python3.7
        docker build -t ${REPOSITORY}:${TAG} --file cuda/Dockerfile .
        docker push ${REPOSITORY}:${TAG}
