name: docker build

on:
  push:
    branches:
      - master

env:
  REPOSITORY: kumassy/foo-bar-images

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login GitHub Registry
      run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}

    - name: cuda image
      run: |
        # IMAGE_NAME=cuda:${GITHUB_REF#refs/heads/}
        IMAGE_NAME=cuda:latest
        docker build -t docker.pkg.github.com/${REPOSITORY}/${IMAGE_NAME} --file cuda/Dockerfile .
        docker push docker.pkg.github.com/${REPOSITORY}/${IMAGE_NAME}

    - name: python image
      run: |
        IMAGE_NAME=python:latest
        docker build -t docker.pkg.github.com/${REPOSITORY}/${IMAGE_NAME} --file python/Dockerfile .
        docker push docker.pkg.github.com/${REPOSITORY}/${IMAGE_NAME}

    - name: cuda-python image
      run: |
        IMAGE_NAME=cuda-python:latest
        docker build -t docker.pkg.github.com/${REPOSITORY}/${IMAGE_NAME} --file cuda-python/Dockerfile .
        docker push docker.pkg.github.com/${REPOSITORY}/${IMAGE_NAME}
